server:
    port: 8000

logging:
    path: /var/logs/
    file: logs.log
    level:
        root: WARN
        org:
            springframework:
                security: DEBUG

spring:
    datasource:
        url: jbdc:mysql://localhost/readinglist
        username: dbuser
        password: dbpass
        driver-class-name: com.mysql.jbdc.Driver
